import { CATEGORIES } from "@/lib/categories";

import {
  A4_HEIGHT,
  A4_WIDTH,
  PdfDocument,
  truncateToWidth,
} from "../pdf-writer";
import type { ExportFormatSpec, ExportMeta, ExportSelection } from "../types";

const COLUMNS = ["Date", "Category", "Amount", "Description"] as const;

const MARGIN = 44;
const ROW_HEIGHT = 17;
const HEADER_HEIGHT = 22;
const FOOTER_SPACE = 52;
const BODY_SIZE = 9;

// Column geometry, in points from the left edge.
const COL_DATE_X = MARGIN;
const COL_CATEGORY_X = 124;
const COL_AMOUNT_RIGHT = 312;
const COL_DESCRIPTION_X = 326;
const DESCRIPTION_WIDTH = A4_WIDTH - MARGIN - COL_DESCRIPTION_X;
const CONTENT_WIDTH = A4_WIDTH - MARGIN * 2;

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

/**
 * Locale-independent on purpose. `toLocaleDateString` would make the same export
 * render differently on two machines, which is the wrong property for a document
 * people file and compare.
 */
function reportDate(iso: string): string {
  const [year, month, day] = iso.split("-");
  const index = Number(month) - 1;
  if (!MONTHS[index]) return iso;
  return `${MONTHS[index]} ${Number(day)}, ${year}`;
}

/** Deterministic ASCII currency — avoids the non-breaking spaces some locales emit. */
function money(value: number): string {
  const fixed = Math.abs(value).toFixed(2);
  const [whole, cents] = fixed.split(".");
  const grouped = whole.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `${value < 0 ? "-" : ""}$${grouped}.${cents}`;
}

function drawTableHeader(doc: PdfDocument, y: number): number {
  doc.rect(MARGIN, y, CONTENT_WIDTH, HEADER_HEIGHT, { color: 0.93 });
  const baseline = y + 14.5;

  doc.text("Date", COL_DATE_X + 6, baseline, { font: "bold", size: 8.5, color: 0.25 });
  doc.text("Category", COL_CATEGORY_X, baseline, { font: "bold", size: 8.5, color: 0.25 });
  doc.text("Amount", COL_AMOUNT_RIGHT, baseline, {
    font: "bold",
    size: 8.5,
    color: 0.25,
    align: "right",
  });
  doc.text("Description", COL_DESCRIPTION_X, baseline, {
    font: "bold",
    size: 8.5,
    color: 0.25,
  });

  return y + HEADER_HEIGHT;
}

function drawFooter(doc: PdfDocument, pageNumber: number): void {
  const y = A4_HEIGHT - 30;
  doc.line(MARGIN, y - 12, CONTENT_WIDTH, 0.5, 0.88);
  doc.text("Generated by Ledger", MARGIN, y, { size: 7.5, color: 0.55 });
  doc.text(`Page ${pageNumber}`, A4_WIDTH - MARGIN, y, {
    size: 7.5,
    color: 0.55,
    align: "right",
  });
}

function buildPdf(selection: ExportSelection, meta: ExportMeta): Blob {
  const doc = new PdfDocument({ title: "Expense report" });
  let page = 1;
  let y = MARGIN;

  // --- Title block -----------------------------------------------------
  doc.text("Expense Report", MARGIN, y + 18, { font: "bold", size: 20 });
  y += 34;

  doc.text(meta.rangeLabel, MARGIN, y, { size: 9.5, color: 0.35 });
  y += 13;
  doc.text(meta.categoryLabel, MARGIN, y, { size: 9.5, color: 0.35 });
  y += 13;

  const stamp = meta.generatedAt;
  doc.text(
    `Generated ${reportDate(
      `${stamp.getFullYear()}-${String(stamp.getMonth() + 1).padStart(2, "0")}-${String(
        stamp.getDate(),
      ).padStart(2, "0")}`,
    )}`,
    MARGIN,
    y,
    { size: 9.5, color: 0.55 },
  );

  // Headline figures, right-aligned against the title block.
  doc.text(money(selection.total), A4_WIDTH - MARGIN, MARGIN + 18, {
    font: "bold",
    size: 20,
    align: "right",
  });
  doc.text(
    `${selection.rows.length} ${selection.rows.length === 1 ? "expense" : "expenses"}`,
    A4_WIDTH - MARGIN,
    MARGIN + 33,
    { size: 9.5, color: 0.45, align: "right" },
  );

  y += 22;

  // --- Optional summary ------------------------------------------------
  if (meta.includeSummary && selection.byCategory.length > 0) {
    doc.line(MARGIN, y, CONTENT_WIDTH, 0.5, 0.85);
    y += 16;
    doc.text("Summary by category", MARGIN, y, { font: "bold", size: 10 });
    y += 16;

    for (const entry of selection.byCategory) {
      doc.text(entry.label, MARGIN + 6, y, { size: 9, color: 0.2 });
      doc.text(
        `${entry.count} ${entry.count === 1 ? "item" : "items"}`,
        COL_CATEGORY_X + 96,
        y,
        { size: 9, color: 0.55 },
      );
      doc.text(money(entry.total), COL_AMOUNT_RIGHT, y, {
        size: 9,
        align: "right",
      });

      const share = selection.total > 0 ? entry.total / selection.total : 0;
      doc.text(`${Math.round(share * 100)}%`, COL_DESCRIPTION_X, y, {
        size: 9,
        color: 0.55,
      });
      y += 14;
    }

    y += 8;
  }

  // --- Table -----------------------------------------------------------
  y = drawTableHeader(doc, y);

  if (selection.rows.length === 0) {
    doc.text("No expenses matched these filters.", MARGIN + 6, y + 18, {
      size: 9,
      color: 0.5,
    });
  }

  selection.rows.forEach((expense, index) => {
    if (y + ROW_HEIGHT > A4_HEIGHT - FOOTER_SPACE) {
      drawFooter(doc, page);
      doc.addPage();
      page += 1;
      y = MARGIN;
      y = drawTableHeader(doc, y);
    }

    // Zebra striping makes a long table scannable across the page width.
    if (index % 2 === 1) {
      doc.rect(MARGIN, y, CONTENT_WIDTH, ROW_HEIGHT, { color: 0.975 });
    }

    const baseline = y + 11.5;
    doc.text(reportDate(expense.date), COL_DATE_X + 6, baseline, {
      size: BODY_SIZE,
      color: 0.2,
    });
    doc.text(CATEGORIES[expense.category].label, COL_CATEGORY_X, baseline, {
      size: BODY_SIZE,
      color: 0.2,
    });
    doc.text(money(expense.amount), COL_AMOUNT_RIGHT, baseline, {
      size: BODY_SIZE,
      align: "right",
    });
    doc.text(
      truncateToWidth(expense.description, DESCRIPTION_WIDTH - 4, BODY_SIZE),
      COL_DESCRIPTION_X,
      baseline,
      { size: BODY_SIZE, color: 0.2 },
    );

    y += ROW_HEIGHT;
  });

  // --- Total ------------------------------------------------------------
  if (selection.rows.length > 0) {
    if (y + 28 > A4_HEIGHT - FOOTER_SPACE) {
      drawFooter(doc, page);
      doc.addPage();
      page += 1;
      y = MARGIN;
    }
    doc.line(MARGIN, y + 2, CONTENT_WIDTH, 0.8, 0.5);
    doc.text("Total", COL_CATEGORY_X, y + 18, { font: "bold", size: 10 });
    doc.text(money(selection.total), COL_AMOUNT_RIGHT, y + 18, {
      font: "bold",
      size: 10,
      align: "right",
    });
  }

  drawFooter(doc, page);
  return doc.toBlob();
}

export const pdfFormat: ExportFormatSpec = {
  id: "pdf",
  label: "PDF",
  extension: "pdf",
  mimeType: "application/pdf",
  description: "Paginated report with totals. For sharing and filing.",
  columns: COLUMNS,
  previewRow: (expense) => [
    reportDate(expense.date),
    CATEGORIES[expense.category].label,
    money(expense.amount),
    expense.description,
  ],
  supportsSummary: true,
  build: buildPdf,
};
